# 1 "data/maps/InquillHouse1/scripts.pory"

# 2 "data/maps/InquillHouse1/scripts.pory"
InquillHouse1_MapScripts::
# 3 "data/maps/InquillHouse1/scripts.pory"
	.byte 0

InquillHouse1_EventScript_Object1::
# 7 "data/maps/InquillHouse1/scripts.pory"
	msgbox InquillHouse1_Text_Object1, MSGBOX_NPC
	end


InquillHouse1_EventScript_Object2::
# 12 "data/maps/InquillHouse1/scripts.pory"
	msgbox InquillHouse1_Text_Object2, MSGBOX_NPC
	end


InquillHouse1_Text_Object1::
# 16 "data/maps/InquillHouse1/scripts.pory"
	.string "My husband is out in his garden like\n"
	.string "always. I wish he would help around\l"
	.string "the house more.$"

InquillHouse1_Text_Object2::
# 22 "data/maps/InquillHouse1/scripts.pory"
	.string "Zoom! Zoom!$"
