# 1 "data/maps/MintakaHouse1/scripts.pory"

# 2 "data/maps/MintakaHouse1/scripts.pory"
MintakaHouse1_MapScripts::
# 3 "data/maps/MintakaHouse1/scripts.pory"
	.byte 0

MintakaHouse1_EventScript_Object1::
# 7 "data/maps/MintakaHouse1/scripts.pory"
	msgbox MintakaHouse1_Text_Object1, MSGBOX_NPC
	end


MintakaHouse1_Text_Object1::
# 11 "data/maps/MintakaHouse1/scripts.pory"
	.string "Oh, have you come to visit a lonely\n"
	.string "old man? How kind… Even my children\l"
	.string "don’t visit anymore.$"
