voice_group bw_main_3  @ normalized 128-entry selective import
	voice_keysplit voicegroup_keysplit_hgss_piano_2, keysplit_hgss_piano_2_vibraphone_glockglockenspiel  @ 000
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano_custom                                       @ 001
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 002
	voice_keysplit voicegroup_keysplit_hgss_rhodes_1, keysplit_dp_electric_piano_2_rhodes                @ 003
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 004
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 005
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 006
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 007
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 008
	voice_keysplit voicegroup_keysplit_hgss_glockenspiel, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 009
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 010
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 011
	voice_directsound 60, 64, DirectSoundWaveData_dp_808snare_16, 255, 220, 0, 171                         @ 012
	voice_keysplit voicegroup_keysplit_hgss_accordion, keysplit_hgss_organ_accordion_harp_timpani        @ 013
	voice_keysplit voicegroup_keysplit_hgss_tubular_bell, keysplit_dp_pizzicato_music_box                  @ 014
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 015
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar                             @ 016
	voice_keysplit voicegroup_keysplit_hgss_drawbar_organ, keysplit_hgss_organ_accordion_harp_timpani    @ 017
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 018
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 019
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 020
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 021
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 022
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 023
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 024
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass                     @ 025
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar                            @ 026
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_slap_bass, 255, 235, 128, 115                       @ 027
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 028
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_dp_distortion_guitar_2             @ 029
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                               @ 030
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 031
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 032
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 033
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 034
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 035
	voice_keysplit voicegroup_keysplit_hgss_pizzicato, keysplit_hgss_pizzicato                           @ 036
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 037
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 038
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 039
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 040
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 041
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 042
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 043
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 044
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 045
	voice_directsound 60, 0, DirectSoundWaveData_dp_timpany_as_16, 255, 248, 0, 205                          @ 046
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 047
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                                   @ 048
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 049
	voice_keysplit voicegroup_keysplit_hgss_french_horn_solo, keysplit_hgss_french_horn_solo             @ 050
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 051
	voice_directsound 60, 0, DirectSoundWaveData_unused_sc88pro_unison_slap, 255, 165, 180, 216             @ 052
	voice_keysplit voicegroup_keysplit_hgss_synth_bass, keysplit_hgss_synth_bass                            @ 053
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 054
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 055
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 056
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 057
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 058
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 059
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet                        @ 060
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 061
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 062
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 063
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 064
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_2, keysplit_dp_distortion_guitar_2             @ 065
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_distortion_guitar_high, 255, 165, 154, 165  @ 066
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 067
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 068
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 069
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 070
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 071
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 072
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 073
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 0, 255, 127      @ 074
	voice_keysplit voicegroup_keysplit_hgss_orchestral_hit, keysplit_hgss_orchestral_hit                    @ 075
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 076
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 077
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 078
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 079
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 080
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 081
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 082
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 083
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 084
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 085
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 086
	voice_directsound 60, 0, DirectSoundWaveData_hg_039drawbc4, 255, 0, 255, 171                           @ 087
	voice_directsound 60, 0, DirectSoundWaveData_dp_sawtoothlead60, 255, 197, 255, 171                       @ 088
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 089
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 090
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 0, 255, 127     @ 091
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 092
	voice_directsound 60, 0, DirectSoundWaveData_unused_guitar_separates_power_chord, 255, 0, 255, 127     @ 093
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 094
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 095
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_fretless_bass, 255, 253, 0, 149                   @ 096
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 097
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 098
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_flute, 255, 127, 231, 127                         @ 099
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 100
	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0                                @ 101
	voice_noise_alt 60, 0, 0, 0, 1, 6, 0                                                                  @ 102
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 103
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 104
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 105
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 106
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 107
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 108
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 109
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 110
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 111
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 112
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 113
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 114
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 115
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 116
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 117
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 118
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 119
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 120
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 121
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 122
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 123
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 124
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitmajor60, 255, 0, 255, 205                        @ 125
	voice_keysplit_all voicegroup_allkeysplit_bw_drum_4                                                    @ 126
	voice_keysplit_all voicegroup_allkeysplit_bw_drum_3                                                  @ 127
