voice_group bw_main_2  @ normalized 128-entry selective import
	voice_keysplit voicegroup_piano_keysplit, keysplit_piano_custom                                      @ 000
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 001
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 002
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 003
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 004
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 005
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 006
	voice_directsound 60, 0, DirectSoundWaveData_unknown_koto_high, 255, 0, 206, 242                     @ 007
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 008
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 009
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 010
	voice_keysplit voicegroup_keysplit_hgss_marimba, keysplit_hgss_marimba_music_box_sampled_square      @ 011
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 012
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 013
	voice_keysplit voicegroup_keysplit_hgss_tubular_bell, keysplit_dp_pizzicato_music_box                @ 014
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 015
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 016
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 017
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 018
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 019
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar                           @ 020
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 021
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 022
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 023
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 024
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass                     @ 025
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 026
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 027
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 028
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 029
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                               @ 030
	voice_keysplit voicegroup_strings_keysplit, keysplit_strings_custom                                  @ 031
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 032
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 033
	voice_keysplit voicegroup_keysplit_hgss_pizzicato, keysplit_hgss_pizzicato                           @ 034
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 035
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 036
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 037
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 038
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 039
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 040
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 041
	voice_keysplit voicegroup_keysplit_hgss_french_horn_solo, keysplit_hgss_french_horn_solo             @ 042
	voice_keysplit voicegroup_keysplit_hgss_french_horn, keysplit_hgss_french_horn                       @ 043
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 044
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet                             @ 045
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 046
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 047
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 048
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 049
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 050
	voice_directsound 60, 0, DirectSoundWaveData_sd90_classical_whistle, 43, 76, 103, 216                @ 051
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 052
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 053
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 054
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 055
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 056
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 057
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 058
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 059
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 060
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 061
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 062
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 063
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 064
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 065
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 066
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 067
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 068
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 069
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 070
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 071
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 072
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 073
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 074
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 075
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 076
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 077
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 078
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 079
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 080
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 081
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 082
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 083
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 084
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 085
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 086
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 087
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 088
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 089
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 090
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 091
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 092
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 093
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 094
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 095
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 096
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 097
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 098
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 099
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 100
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 101
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 102
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 103
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 104
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 105
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 106
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 107
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 108
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 109
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 110
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 111
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 112
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 113
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 114
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 115
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 116
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 117
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 118
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 119
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 120
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 121
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 122
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 123
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 124
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 125
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 126
	voice_keysplit_all voicegroup_allkeysplit_bw_drum_2                                                  @ 127
