voice_group dppt_main  @ normalized 128-entry selective import
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 000
	voice_keysplit_all voicegroup_allkeysplit_dppt_drum_1                                                @ 001
	voice_keysplit voicegroup_keysplit_dp_piano_1, keysplit_dp_piano_1                                   @ 002
	voice_keysplit voicegroup_keysplit_dp_piano_2, keysplit_dp_piano_2                                   @ 003
	voice_keysplit voicegroup_keysplit_dp_electric_piano_1, keysplit_dp_electric_piano_1                 @ 004
	voice_keysplit voicegroup_keysplit_dp_electric_piano_2, keysplit_dp_electric_piano_2_rhodes          @ 005
	voice_keysplit_all voicegroup_allkeysplit_dppt_drum_2                                                @ 006
	voice_keysplit voicegroup_keysplit_dp_clavinet, keysplit_dp_clavinet                                 @ 007
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 008
	voice_directsound 60, 0, DirectSoundWaveData_dp_glocken_c6_16, 255, 247, 0, 208                      @ 009
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 010
	voice_keysplit voicegroup_keysplit_dp_vibraphone, keysplit_dp_vibraphone                             @ 011
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 012
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 013
	voice_keysplit voicegroup_keysplit_dp_tubular_bell, keysplit_dp_tubular_bell                         @ 014
	voice_keysplit voicegroup_keysplit_dp_trinity_piano, keysplit_dp_trinity_piano                       @ 015
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 016
	voice_keysplit voicegroup_keysplit_dp_rotary_organ, keysplit_dp_rotary_organ                         @ 017
	voice_keysplit voicegroup_keysplit_dp_straight_organ, keysplit_dp_straight_organ                     @ 018
	voice_directsound 60, 0, DirectSoundWaveData_dp_org5_c3_16, 255, 175, 235, 171                       @ 019
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 020
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 021
	voice_directsound 60, 0, DirectSoundWaveData_dp_harmonica_c3_16, 67, 247, 191, 171                   @ 022
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 023
	voice_keysplit voicegroup_keysplit_dp_accoustic_guitar, keysplit_dp_accoustic_guitar                 @ 024
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 025
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 026
	voice_keysplit voicegroup_keysplit_dp_clean_guitar, keysplit_dp_clean_guitar                         @ 027
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 028
	voice_keysplit voicegroup_keysplit_dp_distortion_guitar_1, keysplit_dp_distortion_guitar_1           @ 029
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 030
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 031
	voice_keysplit voicegroup_keysplit_dp_wood_bass_1, keysplit_dp_wood_bass                             @ 032
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 033
	voice_directsound 60, 0, DirectSoundWaveData_dp_pickbass_e1_16, 255, 251, 0, 208                     @ 034
	voice_directsound 60, 0, DirectSoundWaveData_dp_fretlessbass_d1_16, 255, 0, 255, 196                 @ 035
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 036
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 216                     @ 037
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 038
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 222                     @ 039
	voice_keysplit voicegroup_keysplit_dp_violin, keysplit_dp_violin                                     @ 040
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 041
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 042
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 043
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 044
	voice_keysplit voicegroup_keysplit_dp_pizzicato, keysplit_dp_pizzicato_music_box                     @ 045
	voice_keysplit voicegroup_keysplit_dp_harp, keysplit_dp_harp                                         @ 046
	voice_keysplit voicegroup_keysplit_dp_timpani_1, keysplit_dp_timpani                                 @ 047
	voice_keysplit voicegroup_keysplit_dp_strings, keysplit_dp_strings                                   @ 048
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 049
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 050
	voice_keysplit voicegroup_keysplit_dp_timpani_2, keysplit_dp_timpani                                 @ 051
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 052
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 053
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 054
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 055
	voice_keysplit voicegroup_keysplit_dp_trumpet_1, keysplit_dp_trumpet                                 @ 056
	voice_keysplit voicegroup_keysplit_dp_trombone, keysplit_dp_trombone                                 @ 057
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 058
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 059
	voice_keysplit voicegroup_keysplit_dp_french_horn, keysplit_dp_electric_piano_2_rhodes               @ 060
	voice_keysplit voicegroup_keysplit_dp_distortion_guitar_2, keysplit_dp_distortion_guitar_2           @ 061
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 062
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 063
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass_c1_16, 255, 42, 255, 216                     @ 064
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 219, 252, 196                    @ 065
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 066
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 067
	voice_directsound 60, 0, DirectSoundWaveData_dp_oboe_c3_16, 255, 243, 127, 216                       @ 068
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 069
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 070
	voice_directsound 60, 0, DirectSoundWaveData_dp_sy_clarinet_c3_16, 255, 243, 159, 216                @ 071
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 072
	voice_keysplit voicegroup_keysplit_dp_flute, keysplit_dp_flute                                       @ 073
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 074
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 075
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 076
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 077
	voice_directsound 60, 0, DirectSoundWaveData_dp_whistle_c5_16, 255, 247, 78, 196                     @ 078
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 079
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 080
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 081
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 082
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 083
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 084
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 085
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 086
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 087
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 088
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 089
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 090
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 091
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 092
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 093
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 094
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 095
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 096
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 097
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 098
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 099
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 100
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 101
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 102
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 103
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 104
	voice_keysplit voicegroup_keysplit_dp_banjo, keysplit_dp_banjo                                       @ 105
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 106
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 107
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 108
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 109
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 110
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 111
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 112
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 113
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 114
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 115
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 116
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 117
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 118
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 119
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 120
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 121
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 122
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 123
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 124
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 125
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 126
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 127
