voice_group hgss_main  @ normalized 128-entry selective import
	voice_keysplit voicegroup_keysplit_hgss_piano_1, keysplit_hgss_piano_1                               @ 000
	voice_keysplit voicegroup_keysplit_hgss_piano_2, keysplit_hgss_piano_2_vibraphone_glockglockenspiel  @ 001
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 002
	voice_keysplit voicegroup_keysplit_hgss_rhodes_1, keysplit_dp_electric_piano_2_rhodes                @ 003
	voice_keysplit voicegroup_keysplit_hgss_rhodes_2, keysplit_dp_electric_piano_2_rhodes                @ 004
	voice_keysplit voicegroup_keysplit_hgss_vibraphone, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 005
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 006
	voice_keysplit voicegroup_keysplit_hgss_xylophone, keysplit_hgss_xylophone_trumpet                   @ 007
	voice_keysplit voicegroup_keysplit_hgss_tubular_bell, keysplit_dp_pizzicato_music_box                @ 008
	voice_keysplit voicegroup_keysplit_hgss_glockenspiel, keysplit_hgss_piano_2_vibraphone_glockglockenspiel @ 009
	voice_keysplit voicegroup_keysplit_hgss_music_box, keysplit_hgss_marimba_music_box_sampled_square    @ 010
	voice_keysplit voicegroup_keysplit_hgss_drawbar_organ, keysplit_hgss_organ_accordion_harp_timpani    @ 011
	voice_keysplit voicegroup_keysplit_hgss_jazz_organ, keysplit_hgss_organ_accordion_harp_timpani       @ 012
	voice_keysplit voicegroup_keysplit_hgss_accordion, keysplit_hgss_organ_accordion_harp_timpani        @ 013
	voice_keysplit voicegroup_keysplit_hgss_nylon_guitar, keysplit_hgss_guitar                           @ 014
	voice_keysplit voicegroup_keysplit_hgss_martin_guitar, keysplit_hgss_guitar                          @ 015
	voice_keysplit voicegroup_keysplit_hgss_distortion_guitar_1, keysplit_dp_distortion_guitar_2         @ 016
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 017
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 018
	voice_keysplit voicegroup_keysplit_hgss_upright_bass, keysplit_hgss_upright_bass                     @ 019
	voice_keysplit voicegroup_keysplit_hgss_fingered_bass, keysplit_hgss_fingered_bass                   @ 020
	voice_directsound 60, 0, DirectSoundWaveData_dp_slapbass_c1_16, 255, 0, 255, 192                     @ 021
	voice_keysplit voicegroup_keysplit_hgss_synth_bass, keysplit_hgss_synth_bass                         @ 022
	voice_keysplit voicegroup_keysplit_hgss_strings, keysplit_hgss_strings                               @ 023
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 024
	voice_keysplit voicegroup_keysplit_hgss_cello, keysplit_hgss_cello_trombone                          @ 025
	voice_keysplit voicegroup_keysplit_hgss_pizzicato, keysplit_hgss_pizzicato                           @ 026
	voice_keysplit voicegroup_keysplit_hgss_harp, keysplit_hgss_organ_accordion_harp_timpani             @ 027
	voice_keysplit voicegroup_keysplit_hgss_timpani, keysplit_hgss_organ_accordion_harp_timpani          @ 028
	voice_keysplit voicegroup_keysplit_hgss_trumpet, keysplit_hgss_xylophone_trumpet                     @ 029
	voice_keysplit voicegroup_keysplit_hgss_trombone, keysplit_hgss_cello_trombone                       @ 030
	voice_keysplit voicegroup_keysplit_hgss_french_horn_solo, keysplit_hgss_french_horn_solo             @ 031
	voice_keysplit voicegroup_keysplit_hgss_french_horn, keysplit_hgss_french_horn                       @ 032
	voice_keysplit voicegroup_keysplit_hgss_oboe, keysplit_hgss_oboe                                     @ 033
	voice_keysplit voicegroup_keysplit_hgss_clarinet, keysplit_hgss_clarinet                             @ 034
	voice_keysplit voicegroup_keysplit_hgss_flute, keysplit_hgss_flute                                   @ 035
	voice_keysplit voicegroup_keysplit_hgss_bassoon, keysplit_hgss_bassoon                               @ 036
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 037
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 038
	voice_keysplit_all voicegroup_allkeysplit_hgss_drum                                                  @ 039
	voice_keysplit_all voicegroup_allkeysplit_hgss_taiko_drum                                            @ 040
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 041
	voice_keysplit voicegroup_keysplit_hgss_koto, keysplit_hgss_koto                                     @ 042
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 043
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 044
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 045
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 046
	voice_directsound 60, 0, DirectSoundWaveData_sc88pro_bubbles, 255, 0, 255, 0                         @ 047
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 048
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 049
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 050
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 051
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 052
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 053
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 054
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 055
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 056
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 057
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 058
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 059
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 060
	voice_directsound 60, 0, DirectSoundWaveData_dp_orchhitminor60, 255, 197, 255, 171                   @ 061
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 062
	voice_keysplit voicegroup_keysplit_dp_timpani_1, keysplit_dp_timpani                                 @ 063
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 064
	voice_directsound 60, 0, DirectSoundWaveData_dp_synbass2_c1_16, 255, 0, 255, 220                     @ 065
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 066
	voice_keysplit voicegroup_keysplit_hgss_shamisen, keysplit_hgss_shamisen                             @ 067
	voice_directsound 60, 0, DirectSoundWaveData_hg_hyoshigi, 255, 0, 255, 171                           @ 068
	voice_directsound 60, 0, DirectSoundWaveData_hg_kodaiko, 255, 0, 255, 171                            @ 069
	voice_directsound 60, 0, DirectSoundWaveData_hg_tsuzumi, 255, 0, 255, 171                            @ 070
	voice_directsound 60, 0, DirectSoundWaveData_hg_jinglebell, 255, 0, 255, 171                         @ 071
	voice_directsound 60, 0, DirectSoundWaveData_hg_hoohclap, 255, 0, 255, 0                             @ 072
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 073
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 074
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 075
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 076
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 077
	voice_directsound 60, 0, DirectSoundWaveData_dp_altosax_c3_16, 255, 216, 252, 192                    @ 078
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 079
	voice_keysplit voicegroup_keysplit_hgss_piano_4, keysplit_hgss_piano_4                                @ 080
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 081
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 082
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 083
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 084
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 085
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 086
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 087
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 088
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 089
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 090
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 091
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 092
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 093
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 094
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 095
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 096
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 097
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 098
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 099
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 100
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 101
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 102
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 103
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 104
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 105
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 106
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 107
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 108
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 109
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 110
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 111
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 112
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 113
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 114
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 115
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 116
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 117
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 118
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 119
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 120
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 121
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 122
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 123
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 124
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 125
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 126
	voice_square_1 60, 0, 0, 2, 0, 0, 15, 0                                                              @ 127
