# 1 "data/maps/InquillHouse4/scripts.pory"

# 2 "data/maps/InquillHouse4/scripts.pory"
InquillHouse4_MapScripts::
# 3 "data/maps/InquillHouse4/scripts.pory"
	.byte 0

InquillHouse4_EventScript_Object1::
# 7 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object1, MSGBOX_NPC
	end


InquillHouse4_EventScript_Object2::
# 12 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object2, MSGBOX_NPC
	end


InquillHouse4_EventScript_Object3::
# 17 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object3, MSGBOX_NPC
	end


InquillHouse4_EventScript_Object4::
# 22 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object4, MSGBOX_NPC
	end


InquillHouse4_EventScript_Object5::
# 27 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object5, MSGBOX_NPC
	end


InquillHouse4_EventScript_Object6::
# 32 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object6, MSGBOX_NPC
	end


InquillHouse4_EventScript_Object7::
# 37 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object7, MSGBOX_NPC
	end


InquillHouse4_EventScript_Object8::
# 42 "data/maps/InquillHouse4/scripts.pory"
	msgbox InquillHouse4_Text_Object8, MSGBOX_NPC
	end


InquillHouse4_Text_Object1::
# 46 "data/maps/InquillHouse4/scripts.pory"
	.string "Here kitty kitty! Here kitty!\n"
	.string "Who’s a good boy!$"

InquillHouse4_Text_Object2::
# 51 "data/maps/InquillHouse4/scripts.pory"
	.string "When we took our Persians to the\n"
	.string "Pokémon breeders outside town, we\l"
	.string "never expected a litter this big…$"

InquillHouse4_Text_Object3::
# 57 "data/maps/InquillHouse4/scripts.pory"
	.string "The Persian is eyeing you carefully.$"

InquillHouse4_Text_Object4::
# 61 "data/maps/InquillHouse4/scripts.pory"
	.string "Me-owth!$"

InquillHouse4_Text_Object5::
# 65 "data/maps/InquillHouse4/scripts.pory"
	.string "Meow-meow-meowth.$"

InquillHouse4_Text_Object6::
# 69 "data/maps/InquillHouse4/scripts.pory"
	.string "Purrrrsian.$"

InquillHouse4_Text_Object7::
# 73 "data/maps/InquillHouse4/scripts.pory"
	.string "Meoowrr!$"

InquillHouse4_Text_Object8::
# 77 "data/maps/InquillHouse4/scripts.pory"
	.string "This Meowth looks very contented.$"
