# 1 "data/maps/InquillHouse3/scripts.pory"

# 2 "data/maps/InquillHouse3/scripts.pory"
InquillHouse3_MapScripts::
# 3 "data/maps/InquillHouse3/scripts.pory"
	.byte 0

InquillHouse3_EventScript_Object1::
# 7 "data/maps/InquillHouse3/scripts.pory"
	msgbox InquillHouse3_Text_Object1, MSGBOX_NPC
	end


InquillHouse3_EventScript_Object2::
# 12 "data/maps/InquillHouse3/scripts.pory"
	msgbox InquillHouse3_Text_Object2, MSGBOX_NPC
	end


InquillHouse3_Text_Object1::
# 16 "data/maps/InquillHouse3/scripts.pory"
	.string "Oh dear, are you out on your own?\n"
	.string "Feel free to stay for dinner.$"

InquillHouse3_Text_Object2::
# 21 "data/maps/InquillHouse3/scripts.pory"
	.string "I’m supposed to be eating my dinner,\n"
	.string "but I’m so close to beating this game!$"
