#ifndef GUARD_CONSTANTS_BLACKJACK_H
#define GUARD_CONSTANTS_BLACKJACK_H

// Returned in VAR_RESULT when the StartBlackJack special finishes.
#define BLACKJACK_RESULT_LOSS 0
#define BLACKJACK_RESULT_WIN  1
#define BLACKJACK_RESULT_DRAW 2
#define BLACKJACK_RESULT_QUIT 3

#endif // GUARD_CONSTANTS_BLACKJACK_H
