#ifndef GUARD_CONSTANTS_CUSTOM_MAP_COMPAT_H
#define GUARD_CONSTANTS_CUSTOM_MAP_COMPAT_H

// Stock story scripts remain linked even when a custom project replaces their maps.
// Keep references to removed object events inert without exposing these fallbacks to C.

#ifndef LOCALID_BIRCHS_LAB_CHIKORITA_BALL
#define LOCALID_BIRCHS_LAB_CHIKORITA_BALL 0
#endif

#ifndef LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL
#define LOCALID_BIRCHS_LAB_CYNDAQUIL_BALL 0
#endif

#ifndef LOCALID_BIRCHS_LAB_RIVAL
#define LOCALID_BIRCHS_LAB_RIVAL 0
#endif

#ifndef LOCALID_BIRCHS_LAB_TOTODILE_BALL
#define LOCALID_BIRCHS_LAB_TOTODILE_BALL 0
#endif

#ifndef LOCALID_BRIDGE_KECLEON
#define LOCALID_BRIDGE_KECLEON 0
#endif

#ifndef LOCALID_BRIDGE_KECLEON_SHADOW
#define LOCALID_BRIDGE_KECLEON_SHADOW 0
#endif

#ifndef LOCALID_CHALLENGE_BIKER
#define LOCALID_CHALLENGE_BIKER 0
#endif

#ifndef LOCALID_DAYCARE_MAN
#define LOCALID_DAYCARE_MAN 0
#endif

#ifndef LOCALID_DEWFORD_BOAT
#define LOCALID_DEWFORD_BOAT 0
#endif

#ifndef LOCALID_GYM_BOY
#define LOCALID_GYM_BOY 0
#endif

#ifndef LOCALID_KIRI
#define LOCALID_KIRI 0
#endif

#ifndef LOCALID_LAVARIDGE_RIVAL
#define LOCALID_LAVARIDGE_RIVAL 0
#endif

#ifndef LOCALID_LAVARIDGE_RIVAL_ON_BIKE
#define LOCALID_LAVARIDGE_RIVAL_ON_BIKE 0
#endif

#ifndef LOCALID_LITTLEROOT_BIRCH
#define LOCALID_LITTLEROOT_BIRCH 0
#endif

#ifndef LOCALID_LITTLEROOT_MOM
#define LOCALID_LITTLEROOT_MOM 0
#endif

#ifndef LOCALID_LITTLEROOT_RIVAL
#define LOCALID_LITTLEROOT_RIVAL 0
#endif

#ifndef LOCALID_MAUVILLE_SCOTT
#define LOCALID_MAUVILLE_SCOTT 0
#endif

#ifndef LOCALID_METEOR_FALLS_AQUA_GRUNT_1
#define LOCALID_METEOR_FALLS_AQUA_GRUNT_1 0
#endif

#ifndef LOCALID_METEOR_FALLS_AQUA_GRUNT_2
#define LOCALID_METEOR_FALLS_AQUA_GRUNT_2 0
#endif

#ifndef LOCALID_METEOR_FALLS_ARCHIE
#define LOCALID_METEOR_FALLS_ARCHIE 0
#endif

#ifndef LOCALID_METEOR_FALLS_MAGMA_GRUNT_1
#define LOCALID_METEOR_FALLS_MAGMA_GRUNT_1 0
#endif

#ifndef LOCALID_METEOR_FALLS_MAGMA_GRUNT_2
#define LOCALID_METEOR_FALLS_MAGMA_GRUNT_2 0
#endif

#ifndef LOCALID_MOSSDEEP_GRUNT_1
#define LOCALID_MOSSDEEP_GRUNT_1 0
#endif

#ifndef LOCALID_MOSSDEEP_GRUNT_2
#define LOCALID_MOSSDEEP_GRUNT_2 0
#endif

#ifndef LOCALID_MOSSDEEP_GRUNT_3
#define LOCALID_MOSSDEEP_GRUNT_3 0
#endif

#ifndef LOCALID_MOSSDEEP_GRUNT_4
#define LOCALID_MOSSDEEP_GRUNT_4 0
#endif

#ifndef LOCALID_MOSSDEEP_MAXIE
#define LOCALID_MOSSDEEP_MAXIE 0
#endif

#ifndef LOCALID_PETALBURG_BOY
#define LOCALID_PETALBURG_BOY 0
#endif

#ifndef LOCALID_PETALBURG_SCOTT
#define LOCALID_PETALBURG_SCOTT 0
#endif

#ifndef LOCALID_PETALBURG_WALLY
#define LOCALID_PETALBURG_WALLY 0
#endif

#ifndef LOCALID_PETALBURG_WALLYS_DAD
#define LOCALID_PETALBURG_WALLYS_DAD 0
#endif

#ifndef LOCALID_PETALBURG_WOODS_DEVON_EMPLOYEE
#define LOCALID_PETALBURG_WOODS_DEVON_EMPLOYEE 0
#endif

#ifndef LOCALID_PETALBURG_WOODS_GRUNT
#define LOCALID_PETALBURG_WOODS_GRUNT 0
#endif

#ifndef LOCALID_RIVALS_HOUSE_1F_MOM
#define LOCALID_RIVALS_HOUSE_1F_MOM 0
#endif

#ifndef LOCALID_RIVALS_HOUSE_1F_RIVAL
#define LOCALID_RIVALS_HOUSE_1F_RIVAL 0
#endif

#ifndef LOCALID_RIVALS_HOUSE_2F_RIVAL
#define LOCALID_RIVALS_HOUSE_2F_RIVAL 0
#endif

#ifndef LOCALID_ROUTE101_BIRCH
#define LOCALID_ROUTE101_BIRCH 0
#endif

#ifndef LOCALID_ROUTE101_ZIGZAGOON
#define LOCALID_ROUTE101_ZIGZAGOON 0
#endif

#ifndef LOCALID_ROUTE103_RIVAL
#define LOCALID_ROUTE103_RIVAL 0
#endif

#ifndef LOCALID_ROUTE104_BOAT
#define LOCALID_ROUTE104_BOAT 0
#endif

#ifndef LOCALID_ROUTE104_BRINEY
#define LOCALID_ROUTE104_BRINEY 0
#endif

#ifndef LOCALID_ROUTE104_RIVAL
#define LOCALID_ROUTE104_RIVAL 0
#endif

#ifndef LOCALID_ROUTE109_BOAT
#define LOCALID_ROUTE109_BOAT 0
#endif

#ifndef LOCALID_ROUTE109_BRINEY
#define LOCALID_ROUTE109_BRINEY 0
#endif

#ifndef LOCALID_ROUTE110_BIRCH
#define LOCALID_ROUTE110_BIRCH 0
#endif

#ifndef LOCALID_ROUTE110_RIVAL
#define LOCALID_ROUTE110_RIVAL 0
#endif

#ifndef LOCALID_ROUTE110_RIVAL_ON_BIKE
#define LOCALID_ROUTE110_RIVAL_ON_BIKE 0
#endif

#ifndef LOCALID_ROUTE111_PLAYER_FALLING
#define LOCALID_ROUTE111_PLAYER_FALLING 0
#endif

#ifndef LOCALID_ROUTE111_ROCK_SMASH_MAN
#define LOCALID_ROUTE111_ROCK_SMASH_MAN 0
#endif

#ifndef LOCALID_ROUTE111_VICKY
#define LOCALID_ROUTE111_VICKY 0
#endif

#ifndef LOCALID_ROUTE111_VICTOR
#define LOCALID_ROUTE111_VICTOR 0
#endif

#ifndef LOCALID_ROUTE111_VICTORIA
#define LOCALID_ROUTE111_VICTORIA 0
#endif

#ifndef LOCALID_ROUTE111_VIVI
#define LOCALID_ROUTE111_VIVI 0
#endif

#ifndef LOCALID_ROUTE112_GRUNT_1
#define LOCALID_ROUTE112_GRUNT_1 0
#endif

#ifndef LOCALID_ROUTE112_GRUNT_2
#define LOCALID_ROUTE112_GRUNT_2 0
#endif

#ifndef LOCALID_ROUTE116_BRINEY
#define LOCALID_ROUTE116_BRINEY 0
#endif

#ifndef LOCALID_ROUTE116_WANDAS_BF
#define LOCALID_ROUTE116_WANDAS_BF 0
#endif

#ifndef LOCALID_ROUTE118_STEVEN
#define LOCALID_ROUTE118_STEVEN 0
#endif

#ifndef LOCALID_ROUTE119_RIVAL
#define LOCALID_ROUTE119_RIVAL 0
#endif

#ifndef LOCALID_ROUTE119_RIVAL_ON_BIKE
#define LOCALID_ROUTE119_RIVAL_ON_BIKE 0
#endif

#ifndef LOCALID_ROUTE119_SCOTT
#define LOCALID_ROUTE119_SCOTT 0
#endif

#ifndef LOCALID_ROUTE120_STEVEN
#define LOCALID_ROUTE120_STEVEN 0
#endif

#ifndef LOCALID_ROUTE121_GRUNT_1
#define LOCALID_ROUTE121_GRUNT_1 0
#endif

#ifndef LOCALID_ROUTE121_GRUNT_2
#define LOCALID_ROUTE121_GRUNT_2 0
#endif

#ifndef LOCALID_ROUTE121_GRUNT_3
#define LOCALID_ROUTE121_GRUNT_3 0
#endif

#ifndef LOCALID_RUSTBORO_GRUNT
#define LOCALID_RUSTBORO_GRUNT 0
#endif

#ifndef LOCALID_RUSTBORO_LITTLE_GIRL
#define LOCALID_RUSTBORO_LITTLE_GIRL 0
#endif

#ifndef LOCALID_RUSTBORO_RIVAL
#define LOCALID_RUSTBORO_RIVAL 0
#endif

#ifndef LOCALID_RUSTBORO_SCIENTIST
#define LOCALID_RUSTBORO_SCIENTIST 0
#endif

#ifndef LOCALID_RUSTURF_TUNNEL_BRINEY
#define LOCALID_RUSTURF_TUNNEL_BRINEY 0
#endif

#ifndef LOCALID_RUSTURF_TUNNEL_PEEKO
#define LOCALID_RUSTURF_TUNNEL_PEEKO 0
#endif

#ifndef LOCALID_RUSTURF_TUNNEL_WANDA
#define LOCALID_RUSTURF_TUNNEL_WANDA 0
#endif

#ifndef LOCALID_SLATEPORT_CAPT_STERN
#define LOCALID_SLATEPORT_CAPT_STERN 0
#endif

#ifndef LOCALID_SLATEPORT_COOK
#define LOCALID_SLATEPORT_COOK 0
#endif

#ifndef LOCALID_SLATEPORT_FAT_MAN
#define LOCALID_SLATEPORT_FAT_MAN 0
#endif

#ifndef LOCALID_SLATEPORT_GIRL
#define LOCALID_SLATEPORT_GIRL 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_1
#define LOCALID_SLATEPORT_GRUNT_1 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_11
#define LOCALID_SLATEPORT_GRUNT_11 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_2
#define LOCALID_SLATEPORT_GRUNT_2 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_3
#define LOCALID_SLATEPORT_GRUNT_3 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_4
#define LOCALID_SLATEPORT_GRUNT_4 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_5
#define LOCALID_SLATEPORT_GRUNT_5 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_6
#define LOCALID_SLATEPORT_GRUNT_6 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_7
#define LOCALID_SLATEPORT_GRUNT_7 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_8
#define LOCALID_SLATEPORT_GRUNT_8 0
#endif

#ifndef LOCALID_SLATEPORT_GRUNT_9
#define LOCALID_SLATEPORT_GRUNT_9 0
#endif

#ifndef LOCALID_SLATEPORT_MAN_1
#define LOCALID_SLATEPORT_MAN_1 0
#endif

#ifndef LOCALID_SLATEPORT_OLD_WOMAN
#define LOCALID_SLATEPORT_OLD_WOMAN 0
#endif

#ifndef LOCALID_SLATEPORT_SCOTT
#define LOCALID_SLATEPORT_SCOTT 0
#endif

#ifndef LOCALID_SLATEPORT_TY
#define LOCALID_SLATEPORT_TY 0
#endif

#ifndef LOCALID_SOOTOPOLIS_ARCHIE
#define LOCALID_SOOTOPOLIS_ARCHIE 0
#endif

#ifndef LOCALID_SOOTOPOLIS_GROUDON
#define LOCALID_SOOTOPOLIS_GROUDON 0
#endif

#ifndef LOCALID_SOOTOPOLIS_KYOGRE
#define LOCALID_SOOTOPOLIS_KYOGRE 0
#endif

#ifndef LOCALID_SOOTOPOLIS_MANIAC
#define LOCALID_SOOTOPOLIS_MANIAC 0
#endif

#ifndef LOCALID_SOOTOPOLIS_MAXIE
#define LOCALID_SOOTOPOLIS_MAXIE 0
#endif

#ifndef LOCALID_SOOTOPOLIS_NINJA_BOY
#define LOCALID_SOOTOPOLIS_NINJA_BOY 0
#endif

#ifndef LOCALID_SOOTOPOLIS_RAYQUAZA
#define LOCALID_SOOTOPOLIS_RAYQUAZA 0
#endif

#ifndef LOCALID_SOOTOPOLIS_STEVEN
#define LOCALID_SOOTOPOLIS_STEVEN 0
#endif

#ifndef LOCALID_SOOTOPOLIS_WALLACE
#define LOCALID_SOOTOPOLIS_WALLACE 0
#endif

#ifndef LOCALID_SOOTOPOLIS_WOMAN_1
#define LOCALID_SOOTOPOLIS_WOMAN_1 0
#endif

#endif // GUARD_CONSTANTS_CUSTOM_MAP_COMPAT_H

