#ifndef GUARD_SLIDING_PUZZLES_CONSTANTS_H
#define GUARD_SLIDING_PUZZLES_CONSTANTS_H

#define SLIDING_PUZZLE_KABUTO      0
#define SLIDING_PUZZLE_OMANYTE     1
#define SLIDING_PUZZLE_AERODACTYL  2
#define SLIDING_PUZZLE_HO_OH       3
#define SLIDING_PUZZLE_FLYING_BIRD 4
#define SLIDING_PUZZLE_FOREST_BIRD 5
#define SLIDING_PUZZLE_DUCK_BOAT   6
#define SLIDING_PUZZLE_SOLVED      7

#define SLIDING_PUZZLE_COUNT       8

#endif // GUARD_SLIDING_PUZZLES_CONSTANTS_H
