# 1 "data/maps/MintakaHouse4/scripts.pory"

# 2 "data/maps/MintakaHouse4/scripts.pory"
MintakaHouse4_MapScripts::
# 3 "data/maps/MintakaHouse4/scripts.pory"
	.byte 0

MintakaHouse4_EventScript_Object1::
# 7 "data/maps/MintakaHouse4/scripts.pory"
	msgbox MintakaHouse4_Text_Object1, MSGBOX_NPC
	end


MintakaHouse4_EventScript_Object2::
# 12 "data/maps/MintakaHouse4/scripts.pory"
	msgbox MintakaHouse4_Text_Object2, MSGBOX_NPC
	end


MintakaHouse4_EventScript_Object3::
# 17 "data/maps/MintakaHouse4/scripts.pory"
	msgbox MintakaHouse4_Text_Object3, MSGBOX_NPC
	end


MintakaHouse4_Text_Object1::
# 21 "data/maps/MintakaHouse4/scripts.pory"
	.string "I appreciate my wife wanting to take\n"
	.string "care of this Grimer, but it stinks.$"

MintakaHouse4_Text_Object2::
# 26 "data/maps/MintakaHouse4/scripts.pory"
	.string "We pulled this Grimer up while fishing\n"
	.string "in the harbour. They’re becoming more\l"
	.string "common, which isn’t a good sign.\p"
	.string "But… It’s kind of cute, isn’t it?$"

MintakaHouse4_Text_Object3::
# 33 "data/maps/MintakaHouse4/scripts.pory"
	.string "Griii-gri-mer!$"
