# 1 "data/maps/InquillHouse2/scripts.pory"

# 2 "data/maps/InquillHouse2/scripts.pory"
InquillHouse2_MapScripts::
# 3 "data/maps/InquillHouse2/scripts.pory"
	.byte 0

InquillHouse2_EventScript_Object1::
# 7 "data/maps/InquillHouse2/scripts.pory"
	msgbox InquillHouse2_Text_Object1, MSGBOX_NPC
	end


InquillHouse2_EventScript_Object2::
# 12 "data/maps/InquillHouse2/scripts.pory"
	msgbox InquillHouse2_Text_Object2, MSGBOX_NPC
	end


InquillHouse2_EventScript_Object3::
# 17 "data/maps/InquillHouse2/scripts.pory"
	msgbox InquillHouse2_Text_Object3, MSGBOX_NPC
	end


InquillHouse2_Text_Object1::
# 21 "data/maps/InquillHouse2/scripts.pory"
	.string "The new hydrology lab is going to\n"
	.string "bring a lot of jobs to town. But it\l"
	.string "will bring a lot of change too.$"

InquillHouse2_Text_Object2::
# 27 "data/maps/InquillHouse2/scripts.pory"
	.string "The house is going to be so quiet\n"
	.string "when our daughter is gone…$"

InquillHouse2_Text_Object3::
# 32 "data/maps/InquillHouse2/scripts.pory"
	.string "I’m going to university this fall.\n"
	.string "I’m so excited to be in the big city!$"
