# 1 "data/maps/InquillTown/scripts.pory"

# 2 "data/maps/InquillTown/scripts.pory"
InquillTown_MapScripts::
# 3 "data/maps/InquillTown/scripts.pory"
	.byte 0

InquillTown_EventScript_Object1::
# 7 "data/maps/InquillTown/scripts.pory"
	msgbox InquillTown_Text_Object1, MSGBOX_NPC
	end


InquillTown_EventScript_Object2::
# 12 "data/maps/InquillTown/scripts.pory"
	msgbox InquillTown_Text_Object2, MSGBOX_NPC
	end


InquillTown_EventScript_Object3::
# 17 "data/maps/InquillTown/scripts.pory"
	msgbox InquillTown_Text_Object3, MSGBOX_NPC
	end


InquillTown_EventScript_Object4::
# 22 "data/maps/InquillTown/scripts.pory"
	msgbox InquillTown_Text_Object4, MSGBOX_NPC
	end


InquillTown_EventScript_Object5::
# 27 "data/maps/InquillTown/scripts.pory"
	msgbox InquillTown_Text_Object5, MSGBOX_NPC
	end


InquillTown_EventScript_Object6::
# 32 "data/maps/InquillTown/scripts.pory"
	msgbox InquillTown_Text_Object6, MSGBOX_NPC
	end


InquillTown_Text_Object1::
# 36 "data/maps/InquillTown/scripts.pory"
	.string "Check out our shop! We’re offering\n"
	.string "a promotional Wailmer Pail to new\l"
	.string "customers.$"

InquillTown_Text_Object2::
# 42 "data/maps/InquillTown/scripts.pory"
	.string "The air in this town is so clean and\n"
	.string "fresh thanks to efforts to keep it\l"
	.string "green.\p"
	.string "That new lab on the edge of town only\n"
	.string "got approved when it promised to use\l"
	.string "clean hydroelectric energy.$"

InquillTown_Text_Object3::
# 51 "data/maps/InquillTown/scripts.pory"
	.string "Ah, I love to stroll and smell the\n"
	.string "flowers. Inquill may be uneventful,\l"
	.string "but it’s beautiful.$"

InquillTown_Text_Object4::
# 57 "data/maps/InquillTown/scripts.pory"
	.string "I smell something delicious from in\n"
	.string "the house. I need to finish watering\l"
	.string "these plants and get inside.$"

InquillTown_Text_Object5::
# 63 "data/maps/InquillTown/scripts.pory"
	.string "Are you here to challenge the gym?\n"
	.string "Their Pokémon are so cute!$"

InquillTown_Text_Object6::
# 68 "data/maps/InquillTown/scripts.pory"
	.string "Sigh… Can’t you see I’m on break, kid?\p"
	.string "You’ll have to go in the mart if you\n"
	.string "want to buy items.$"
